language: cpp
compiler:
  - gcc
  - clang

sudo : required

dist: trusty

# Required packages
before_install:
 - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
 - sudo apt-get update -qq
 
install:
 - sudo apt-get install -qq libboost1.55-all-dev
 - sudo apt-get install -qq cmake
 
# configuration
before_script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug

# make & check
script:
  - make 
  - make test
